### ISSUE TITLE
Add pre-commit to zarhus/docs

### ISSUE THREAD

**Issue by DaniilKl** [zarhus/zarhus-issues#14]
pre-commit is very useful for quick spell-check. We may get inspired by `dasharo/docs` and by `3mdeb/hooks`.

**Comment by m-iwanicki** [comment]
I agree, just now I also wanted pre-commit to be available.

**Comment by m-iwanicki** [comment]
@DaniilKl Added basic pre-commit without fixes. We could probably also add lychee, what do you think? After that there is still README.md to fix (probably just uncomment correct sections?)
