### ISSUE TITLE
Disable/move issues from org repositories to zarhus/zarhus-issues

### ISSUE THREAD

**Issue by tym2k1** [zarhus/zarhus-issues#17]
Repositories with still enabled issues:
- [meta-zarhus](https://github.com/zarhus/meta-zarhus/issues)
- [docs](https://github.com/zarhus/docs)
- [listmonk-api](https://github.com/zarhus/listmonk-api)
- [meta-zarhus-bsp-rockchip](https://github.com/zarhus/meta-zarhus-bsp-rockchip)
- [meta-zarhus-webkit](https://github.com/zarhus/meta-zarhus-webkit)

All issues should be ported to [zarhus/zarhus-issues](https://github.com/zarhus/zarhus-issues).

As of writing this issue there are [discussions of introducing monorepo for meta-zarhus](https://github.com/zarhus/meta-zarhus/pull/18). It's important not to lose any issues/PR's from the merged repositories.

**Comment by tym2k1** [comment]
Ported issues from meta-zarhus to zarhus-issues but they still need to be disabled from the mentioned repositories

**Comment by macpijan** [comment]
Disabled except for the [meta-zarhus-bsp-rockchip](https://github.com/zarhus/meta-zarhus-bsp-rockchip) which is already archived and cannot remove issues, but new ones cannot be created, which is probably fine.

Shall I  archive webkit layer as well?

**Comment by tym2k1** [comment]
There is [one branch there without PR that adds support for `zarhus-memtest`](https://github.com/zarhus/meta-zarhus-webkit/tree/cog-memtest/recipes-tools/zarhus-memtest). @PLangowski what's the state of this feature? Should it be incorporated into meta-zarhus-webkit in the meta-zarhus monorepo?

**Comment by PLangowski** [comment]
The things from that branch were moved to `meta-zarhus`. The branch is now deleted.

**Comment by tym2k1** [comment]
Ok I [see it](https://github.com/zarhus/meta-zarhus/tree/mem-usage). @macpijan then webkit layer can also be archived

**Comment by tym2k1** [comment]
All issues ported and both `meta-zarhus-webkit` and `meta-zarhus-bsp-rockchip` archived. Closing the issue
