### ISSUE TITLE
Roadmap Request

### ISSUE THREAD

**Issue by pietrushnic** [zarhus/zarhus-issues#2]
I would appreciate it if you created a roadmap here in the form of milestones. There is a lot to do, and I would like to see what progress we make at least quarterly. One of the most important things is to clean up stuff with repositories. I suggest migrating all Yocto-related projects under Zarhus. Fix licenses. Make some marketing.

**Comment by pietrushnic** [comment]
This Roadmap should be presented on DUG#6, which is 13th June.

We are missing references to a presentation from DUG#5. It could serve as the basis for educational purposes.

**Comment by artur-rs** [comment]
@pietrushnic added some new roadmaps: https://github.com/zarhus/zarhus-issues/milestones
* marketing v0.1.0 - let's try to finalize in this month
* marketing v0.2.0 - needs planning, let's treat it as an aggregator for now
* products v0.1.0 - this should evolve into more mature roadmaps in the future, let's treat it as a technical backlog for next planning

**Comment by pietrushnic** [comment]
@artur-rs Great, I would appreciate CfP for DUG#7/vPub 0xC: https://cfp.3mdeb.com/developers-vpub-0xc-2024/

**Comment by artur-rs** [comment]
@pietrushnic CFP for DUG 8 has been sent, closing this issue
